-- MySQL Script generated by MySQL Workbench
-- Thu Feb 17 11:13:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema narc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema narc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `narc` DEFAULT CHARACTER SET utf8 ;
USE `narc` ;

-- -----------------------------------------------------
-- Table `narc`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `narc`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(200) NULL,
  `firstname` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `password` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `narc`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `narc`.`topic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `description` VARCHAR(2000) NULL,
  `creator` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_topic_user_idx` (`creator` ASC) VISIBLE,
  CONSTRAINT `fk_topic_user`
    FOREIGN KEY (`creator`)
    REFERENCES `narc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `narc`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `narc`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `topic_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `content` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_topic1_idx` (`topic_id` ASC) VISIBLE,
  INDEX `fk_post_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_topic1`
    FOREIGN KEY (`topic_id`)
    REFERENCES `narc`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `narc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `narc`.`topic_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `narc`.`topic_member` (
  `uid` INT NOT NULL,
  `tid` INT NOT NULL,
  INDEX `fk_topic_member_user1_idx` (`uid` ASC) VISIBLE,
  INDEX `fk_topic_member_topic1_idx` (`tid` ASC) VISIBLE,
  CONSTRAINT `fk_topic_member_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `narc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topic_member_topic1`
    FOREIGN KEY (`tid`)
    REFERENCES `narc`.`topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `narc`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `narc`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `text` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comment_post1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `narc`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `narc`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
